easy_admin:
    site_name: PocketInnoCity

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'User', label: 'Users', icon: 'user' }
            - { entity: 'City', label: 'Cities', icon: 'map-marker' }
            - { entity: 'Idea', label: 'Ideas', icon: 'comments' }

    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - pseudo
                    - { property: 'mail', type: 'email' }
                    - city
                sort: ['pseudo', 'ASC']
                filters: ['city']
            edit:
                fields:
                    - 'pseudo'
                    - { property: 'password', type: 'password' }

        City:
            class: App\Entity\City
            list:
                fields:
                    - name
                    - zip
                    - country
                sort: ['name', 'ASC']
                filters: ['country']
            edit:
                fields:
                    - 'name'
                    - 'zip'
                    - 'country'
                    - 'ideas'

        Idea:
            class: App\Entity\Idea
            list:
                fields:
                    - author
                    - city
                    - title
                    - content
                    - likes
                sort: ['city', 'ASC']
                filters: ['city', 'author']
