version: '3.1'

services:
  database:
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PIC
    ports: [3306]

  redis:
    image: redis
    ports: [6379]
